services:
  postgres:
    container_name: postgres
    image: 'postgres:latest'
    env_file:
      - env/postgres.env
    ports:
      - '5432:5432'

  spring:
    container_name: littlepm-content-service
    build:
      context: .
    env_file:
      - ./env/config.env
    ports:
      - "8080:8080"
    depends_on:
      - postgres
