/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pm.little.api.controllers;

import jakarta.annotation.Generated;
import pm.little.api.models.dto.*;
import pm.little.api.models.FormInstance;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-04T00:03:08.519382+02:00[Europe/Prague]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "form-instances", description = "the form-instances API")
public interface FormInstancesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /form-instances/{form_blueprint_uuid}/{user_uuid} : Delete a form instance
     *
     * @param formBlueprintUuid The UUID of the form blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @return No Content (status code 204)
     */
    @Operation(
        operationId = "formInstancesFormBlueprintUuidUserUuidDelete",
        summary = "Delete a form instance",
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content")
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/form-instances/{form_blueprint_uuid}/{user_uuid}"
    )
    
    default ResponseEntity<Void> formInstancesFormBlueprintUuidUserUuidDelete(
        @Parameter(name = "form_blueprint_uuid", description = "The UUID of the form blueprint", required = true, in = ParameterIn.PATH) @PathVariable("form_blueprint_uuid") UUID formBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /form-instances/{form_blueprint_uuid}/{user_uuid} : Get a user&#39;s specific form instance
     *
     * @param formBlueprintUuid The UUID of the form blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @return FormInstance (status code 200)
     */
    @Operation(
        operationId = "formInstancesFormBlueprintUuidUserUuidGet",
        summary = "Get a user's specific form instance",
        responses = {
            @ApiResponse(responseCode = "200", description = "FormInstance", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FormDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/form-instances/{form_blueprint_uuid}/{user_uuid}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<FormDTO> formInstancesFormBlueprintUuidUserUuidGet(
        @Parameter(name = "form_blueprint_uuid", description = "The UUID of the form blueprint", required = true, in = ParameterIn.PATH) @PathVariable("form_blueprint_uuid") UUID formBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"blueprint\" : { \"callback_url\" : \"callback_url\", \"form_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"description\" : \"description\", \"title\" : \"title\" }, \"instance\" : { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /form-instances/{form_blueprint_uuid}/{user_uuid} : Update a form instance
     *
     * @param formBlueprintUuid The UUID of the form blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @param formInstance  (required)
     * @return Updated form instance (status code 200)
     */
    @Operation(
        operationId = "formInstancesFormBlueprintUuidUserUuidPut",
        summary = "Update a form instance",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated form instance", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FormDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/form-instances/{form_blueprint_uuid}/{user_uuid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FormDTO> formInstancesFormBlueprintUuidUserUuidPut(
        @Parameter(name = "form_blueprint_uuid", description = "The UUID of the form blueprint", required = true, in = ParameterIn.PATH) @PathVariable("form_blueprint_uuid") UUID formBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid,
        @Parameter(name = "FormInstance", description = "", required = true) @Valid @RequestBody FormInstance formInstance
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"blueprint\" : { \"callback_url\" : \"callback_url\", \"form_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"description\" : \"description\", \"title\" : \"title\" }, \"instance\" : { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /form-instances : List all form instances
     *
     * @param userUuid The UUID of the user (required)
     * @param limit Limit of the list (required)
     * @param offset Offset of the list (required)
     * @return A list of FormInstance (status code 200)
     */
    @Operation(
        operationId = "formInstancesGet",
        summary = "List all form instances",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of FormInstance", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FormDTO.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/form-instances",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<FormDTO>> formInstancesGet(
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid,
        @NotNull @Parameter(name = "limit", description = "Limit of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = true) Integer limit,
        @NotNull @Parameter(name = "offset", description = "Offset of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = true) Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"blueprint\" : { \"callback_url\" : \"callback_url\", \"form_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"description\" : \"description\", \"title\" : \"title\" }, \"instance\" : { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }, { \"blueprint\" : { \"callback_url\" : \"callback_url\", \"form_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"description\" : \"description\", \"title\" : \"title\" }, \"instance\" : { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /form-instances : Create a form instance (user)
     *
     * @param formInstance  (required)
     * @return Created form instance (status code 200)
     */
    @Operation(
        operationId = "formInstancesPost",
        summary = "Create a form instance (user)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Created form instance", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FormDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/form-instances",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FormDTO> formInstancesPost(
        @Parameter(name = "FormInstance", description = "", required = true) @Valid @RequestBody FormInstance formInstance
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"blueprint\" : { \"callback_url\" : \"callback_url\", \"form_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\", \"description\" : \"description\", \"title\" : \"title\" }, \"instance\" : { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
