/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pm.little.api.controllers;

import pm.little.api.models.FormFieldMapper;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-27T23:47:32.256351+01:00[Europe/Prague]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "form-field-mapper", description = "the form-field-mapper API")
public interface FormFieldMapperApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * DELETE /form-field-mapper/{form_blueprint_uuid}/{form_field_uuid} : Delete a form-field mapping (admin only)
     *
     * @param formBlueprintUuid The UUID of the form blueprint (required)
     * @param fieldUuid The UUID of the form field (required)
     * @return No Content (status code 204)
     */
    @Operation(
        operationId = "formFieldMapperFormBlueprintUuidFormFieldUuidDelete",
        summary = "Delete a form-field mapping (admin only)",
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content")
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/form-field-mapper/{form_blueprint_uuid}/{form_field_uuid}"
    )
    
    default ResponseEntity<Void> formFieldMapperFormBlueprintUuidFormFieldUuidDelete(
        @Parameter(name = "form_blueprint_uuid", description = "The UUID of the form blueprint", required = true, in = ParameterIn.PATH) @PathVariable("form_blueprint_uuid") UUID formBlueprintUuid,
        @Parameter(name = "field_uuid", description = "The UUID of the form field", required = true, in = ParameterIn.PATH) @PathVariable("field_uuid") UUID fieldUuid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /form-field-mapper/{form_blueprint_uuid}/{form_field_uuid} : Get a specific form-field mapping
     *
     * @param formBlueprintUuid The UUID of the form blueprint (required)
     * @param fieldUuid The UUID of the form field (required)
     * @return A single FormFieldMapper (status code 200)
     */
    @Operation(
        operationId = "formFieldMapperFormBlueprintUuidFormFieldUuidGet",
        summary = "Get a specific form-field mapping",
        responses = {
            @ApiResponse(responseCode = "200", description = "A single FormFieldMapper", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FormFieldMapper.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/form-field-mapper/{form_blueprint_uuid}/{form_field_uuid}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<FormFieldMapper> formFieldMapperFormBlueprintUuidFormFieldUuidGet(
        @Parameter(name = "form_blueprint_uuid", description = "The UUID of the form blueprint", required = true, in = ParameterIn.PATH) @PathVariable("form_blueprint_uuid") UUID formBlueprintUuid,
        @Parameter(name = "field_uuid", description = "The UUID of the form field", required = true, in = ParameterIn.PATH) @PathVariable("field_uuid") UUID fieldUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"form_field_uuid\" : \"a8494f64-0987-4dd0-8405-df19eb58f2ab\" }, \"order\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /form-field-mapper/{form_blueprint_uuid}/{form_field_uuid} : Update a form-field mapping (admin only)
     *
     * @param formBlueprintUuid The UUID of the form blueprint (required)
     * @param fieldUuid The UUID of the form field (required)
     * @param formFieldMapper  (required)
     * @return Updated form-field mapping (status code 200)
     */
    @Operation(
        operationId = "formFieldMapperFormBlueprintUuidFormFieldUuidPut",
        summary = "Update a form-field mapping (admin only)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated form-field mapping", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FormFieldMapper.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/form-field-mapper/{form_blueprint_uuid}/{form_field_uuid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FormFieldMapper> formFieldMapperFormBlueprintUuidFormFieldUuidPut(
        @Parameter(name = "form_blueprint_uuid", description = "The UUID of the form blueprint", required = true, in = ParameterIn.PATH) @PathVariable("form_blueprint_uuid") UUID formBlueprintUuid,
        @Parameter(name = "field_uuid", description = "The UUID of the form field", required = true, in = ParameterIn.PATH) @PathVariable("field_uuid") UUID fieldUuid,
        @Parameter(name = "FormFieldMapper", description = "", required = true) @Valid @RequestBody FormFieldMapper formFieldMapper
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"form_field_uuid\" : \"a8494f64-0987-4dd0-8405-df19eb58f2ab\" }, \"order\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /form-field-mapper : List all form-field mappings
     *
     * @return A list of FormFieldMapper (status code 200)
     */
    @Operation(
        operationId = "formFieldMapperGet",
        summary = "List all form-field mappings",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of FormFieldMapper", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = FormFieldMapper.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/form-field-mapper",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<FormFieldMapper>> formFieldMapperGet(
        
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"form_field_uuid\" : \"a8494f64-0987-4dd0-8405-df19eb58f2ab\" }, \"order\" : 1 }, { \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"form_field_uuid\" : \"a8494f64-0987-4dd0-8405-df19eb58f2ab\" }, \"order\" : 1 } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /form-field-mapper : Create a form-field mapping (admin only)
     *
     * @param formFieldMapper  (required)
     * @return Created form-field mapping (status code 200)
     */
    @Operation(
        operationId = "formFieldMapperPost",
        summary = "Create a form-field mapping (admin only)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Created form-field mapping", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = FormFieldMapper.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/form-field-mapper",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<FormFieldMapper> formFieldMapperPost(
        @Parameter(name = "FormFieldMapper", description = "", required = true) @Valid @RequestBody FormFieldMapper formFieldMapper
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"id\" : { \"form_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"form_field_uuid\" : \"a8494f64-0987-4dd0-8405-df19eb58f2ab\" }, \"order\" : 1 }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
