/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pm.little.api.controllers;

import pm.little.api.models.TaskBlueprint;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-03-27T23:47:32.256351+01:00[Europe/Prague]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "tasks", description = "the tasks API")
public interface TasksApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /tasks : List task templates
     *
     * @param limit Limit of the list (required)
     * @param offset Offset of the list (required)
     * @return A list of task templates (status code 200)
     */
    @Operation(
        operationId = "tasksGet",
        summary = "List task templates",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of task templates", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskBlueprint.class)))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tasks",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<TaskBlueprint>> tasksGet(
        @NotNull @Parameter(name = "limit", description = "Limit of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = true) Integer limit,
        @NotNull @Parameter(name = "offset", description = "Offset of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = true) Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /tasks : Create task template (admin only)
     *
     * @param taskBlueprint  (required)
     * @return Created task blueprint (status code 200)
     */
    @Operation(
        operationId = "tasksPost",
        summary = "Create task template (admin only)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Created task blueprint", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskBlueprint.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/tasks",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<TaskBlueprint> tasksPost(
        @Parameter(name = "TaskBlueprint", description = "", required = true) @Valid @RequestBody TaskBlueprint taskBlueprint
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /tasks/{task_blueprint_uuid} : Delete task template (admin only)
     *
     * @param taskBlueprintUuid The UUID of the task blueprint (required)
     * @return No Content (status code 204)
     */
    @Operation(
        operationId = "tasksTaskBlueprintUuidDelete",
        summary = "Delete task template (admin only)",
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content")
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/tasks/{task_blueprint_uuid}"
    )
    
    default ResponseEntity<Void> tasksTaskBlueprintUuidDelete(
        @Parameter(name = "task_blueprint_uuid", description = "The UUID of the task blueprint", required = true, in = ParameterIn.PATH) @PathVariable("task_blueprint_uuid") UUID taskBlueprintUuid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /tasks/{task_blueprint_uuid} : Get task template
     *
     * @param taskBlueprintUuid The UUID of the task blueprint (required)
     * @return Task blueprint (status code 200)
     */
    @Operation(
        operationId = "tasksTaskBlueprintUuidGet",
        summary = "Get task template",
        responses = {
            @ApiResponse(responseCode = "200", description = "Task blueprint", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskBlueprint.class))
            })
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/tasks/{task_blueprint_uuid}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<TaskBlueprint> tasksTaskBlueprintUuidGet(
        @Parameter(name = "task_blueprint_uuid", description = "The UUID of the task blueprint", required = true, in = ParameterIn.PATH) @PathVariable("task_blueprint_uuid") UUID taskBlueprintUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /tasks/{task_blueprint_uuid} : Update task template (admin only)
     *
     * @param taskBlueprintUuid The UUID of the task blueprint (required)
     * @param taskBlueprint  (required)
     * @return Updated task blueprint (status code 200)
     */
    @Operation(
        operationId = "tasksTaskBlueprintUuidPut",
        summary = "Update task template (admin only)",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated task blueprint", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskBlueprint.class))
            })
        },
        security = {
            @SecurityRequirement(name = "admin_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/tasks/{task_blueprint_uuid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<TaskBlueprint> tasksTaskBlueprintUuidPut(
        @Parameter(name = "task_blueprint_uuid", description = "The UUID of the task blueprint", required = true, in = ParameterIn.PATH) @PathVariable("task_blueprint_uuid") UUID taskBlueprintUuid,
        @Parameter(name = "TaskBlueprint", description = "", required = true) @Valid @RequestBody TaskBlueprint taskBlueprint
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
