/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.11.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package pm.little.api.controllers;

import jakarta.annotation.Generated;
import pm.little.api.models.dto.*;
import pm.little.api.models.TaskInstance;
import java.util.UUID;
import io.swagger.v3.oas.annotations.ExternalDocumentation;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.Parameters;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import org.springframework.http.HttpStatus;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.context.request.NativeWebRequest;
import org.springframework.web.multipart.MultipartFile;

import javax.validation.Valid;
import javax.validation.constraints.*;
import java.util.List;
import java.util.Map;
import java.util.Optional;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2025-04-04T00:03:08.519382+02:00[Europe/Prague]", comments = "Generator version: 7.11.0")
@Validated
@Tag(name = "task-instances", description = "the task-instances API")
public interface TaskInstancesApi {

    default Optional<NativeWebRequest> getRequest() {
        return Optional.empty();
    }

    /**
     * GET /task-instances : List all task instances
     *
     * @param userUuid The UUID of the user (required)
     * @param limit Limit of the list (required)
     * @param offset Offset of the list (required)
     * @return A list of TaskInstance (status code 200)
     */
    @Operation(
        operationId = "taskInstancesGet",
        summary = "List all task instances",
        responses = {
            @ApiResponse(responseCode = "200", description = "A list of TaskInstance", content = {
                @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = TaskDTO.class)))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/task-instances",
        produces = { "application/json" }
    )
    
    default ResponseEntity<List<TaskDTO>> taskInstancesGet(
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid,
        @NotNull @Parameter(name = "limit", description = "Limit of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "limit", required = true) Integer limit,
        @NotNull @Parameter(name = "offset", description = "Offset of the list", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "offset", required = true) Integer offset
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "[ { \"blueprint\" : { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"progress\" : { \"id\" : { \"task_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }, { \"blueprint\" : { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"progress\" : { \"id\" : { \"task_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } } ]";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * POST /task-instances : Create a new task instance
     *
     * @param taskInstance  (required)
     * @return Created task instance (status code 200)
     */
    @Operation(
        operationId = "taskInstancesPost",
        summary = "Create a new task instance",
        responses = {
            @ApiResponse(responseCode = "200", description = "Created task instance", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/task-instances",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<TaskDTO> taskInstancesPost(
        @Parameter(name = "TaskInstance", description = "", required = true) @Valid @RequestBody TaskInstance taskInstance
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"blueprint\" : { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"progress\" : { \"id\" : { \"task_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * DELETE /task-instances/{task_blueprint_uuid}/{user_uuid} : Delete a task instance
     *
     * @param taskBlueprintUuid The UUID of the task blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @return No Content (status code 204)
     */
    @Operation(
        operationId = "taskInstancesTaskBlueprintUuidUserUuidDelete",
        summary = "Delete a task instance",
        responses = {
            @ApiResponse(responseCode = "204", description = "No Content")
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.DELETE,
        value = "/task-instances/{task_blueprint_uuid}/{user_uuid}"
    )
    
    default ResponseEntity<Void> taskInstancesTaskBlueprintUuidUserUuidDelete(
        @Parameter(name = "task_blueprint_uuid", description = "The UUID of the task blueprint", required = true, in = ParameterIn.PATH) @PathVariable("task_blueprint_uuid") UUID taskBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid
    ) {
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * GET /task-instances/{task_blueprint_uuid}/{user_uuid} : Get a user&#39;s specific task instance
     *
     * @param taskBlueprintUuid The UUID of the task blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @return TaskInstance (status code 200)
     */
    @Operation(
        operationId = "taskInstancesTaskBlueprintUuidUserUuidGet",
        summary = "Get a user's specific task instance",
        responses = {
            @ApiResponse(responseCode = "200", description = "TaskInstance", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.GET,
        value = "/task-instances/{task_blueprint_uuid}/{user_uuid}",
        produces = { "application/json" }
    )
    
    default ResponseEntity<TaskDTO> taskInstancesTaskBlueprintUuidUserUuidGet(
        @Parameter(name = "task_blueprint_uuid", description = "The UUID of the task blueprint", required = true, in = ParameterIn.PATH) @PathVariable("task_blueprint_uuid") UUID taskBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"blueprint\" : { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"progress\" : { \"id\" : { \"task_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }


    /**
     * PUT /task-instances/{task_blueprint_uuid}/{user_uuid} : Update a task instance
     *
     * @param taskBlueprintUuid The UUID of the task blueprint (required)
     * @param userUuid The UUID of the user (required)
     * @param taskInstance  (required)
     * @return Updated task instance (status code 200)
     */
    @Operation(
        operationId = "taskInstancesTaskBlueprintUuidUserUuidPut",
        summary = "Update a task instance",
        responses = {
            @ApiResponse(responseCode = "200", description = "Updated task instance", content = {
                @Content(mediaType = "application/json", schema = @Schema(implementation = TaskDTO.class))
            })
        },
        security = {
            @SecurityRequirement(name = "user_jwt")
        }
    )
    @RequestMapping(
        method = RequestMethod.PUT,
        value = "/task-instances/{task_blueprint_uuid}/{user_uuid}",
        produces = { "application/json" },
        consumes = { "application/json" }
    )
    
    default ResponseEntity<TaskDTO> taskInstancesTaskBlueprintUuidUserUuidPut(
        @Parameter(name = "task_blueprint_uuid", description = "The UUID of the task blueprint", required = true, in = ParameterIn.PATH) @PathVariable("task_blueprint_uuid") UUID taskBlueprintUuid,
        @Parameter(name = "user_uuid", description = "The UUID of the user", required = true, in = ParameterIn.PATH) @PathVariable("user_uuid") UUID userUuid,
        @Parameter(name = "TaskInstance", description = "", required = true) @Valid @RequestBody TaskInstance taskInstance
    ) {
        getRequest().ifPresent(request -> {
            for (MediaType mediaType: MediaType.parseMediaTypes(request.getHeader("Accept"))) {
                if (mediaType.isCompatibleWith(MediaType.valueOf("application/json"))) {
                    String exampleString = "{ \"blueprint\" : { \"description\" : \"description\", \"title\" : \"title\", \"task_blueprint_uuid\" : \"046b6c7f-0b8a-43b9-b35d-6489e6daee91\" }, \"progress\" : { \"id\" : { \"task_blueprint_uuid\" : \"665c599d-5c8d-4d20-aaab-7ffaba150606\", \"user_uuid\" : \"66de88ad-5c8d-4d20-a0ab-bbb7ccc15333\" }, \"status\" : true } }";
                    ApiUtil.setExampleResponse(request, "application/json", exampleString);
                    break;
                }
            }
        });
        return new ResponseEntity<>(HttpStatus.NOT_IMPLEMENTED);

    }

}
